### ISSUE TITLE
Strings are not preserved if they start with 0 and are numbers

### ISSUE THREAD

**Issue by Deliganli** [geirolz/cats-xml#124]
I experimented with the library today, looks very nice thank you for it. I encountered an issue while parsing enum like values.

Strings that are starting with 0 and are numbers (like "01") are not preserved when decoded as `String`, but instead lose the leading 0

Test to reproduce in `FreeCursorSuite:29`;
```scala
  test("FreeCursor.map".fail) {

    val cursor: FreeCursor[Xml, Int] = Root.bar.test.as[Int]
    val node: XmlNode =
      XmlNode("foo")
        .withChildren(
          XmlNode("bar")
            .withChildren(
              XmlNode("test").withText("01")
            )
        )

    assertEquals(
      obtained = cursor.map(_.toString).focus(node),
      expected = Valid("01")
    )
  }
```

results;
```sbt
52:    assertEquals(
53:      obtained = cursor.map(_.toString).focus(node),
values are not the same
=> Obtained
Valid(
  a = "1"
)
=> Diff (- obtained, + expected)
 Valid(
-  a = "1"
+  a = "01"
 )
    at munit.FunSuite.assertEquals(FunSuite.scala:11)
    at cats.xml.cursor.FreeCursorSuite.$anonfun$new$5(FreeCursorSuite.scala:52)
```

It should return "01"

**Comment by geirolz** [comment]
Thanks @Deliganli.
This is definitely a bug, looking into it!

**Comment by Deliganli** [comment]
I just noticed I wrongly used the `Decoder[Int]` in the modified test I left above, sorry for that. 
Maybe example below is more clear on what I tried to do.

```scala
import cats.xml.implicits._
import cats.xml.codec._

val x = xml"""
    <foo>
      <bar>01</bar>
    </foo>
  """
// x: cats.xml.XmlNode = <foo>
//  <bar>1</bar>
// </foo>

case class Bar(v: String)

implicit val barDecoder: Decoder[Bar] = Decoder.fromCursor { c =>
  c.down("bar")
    .as[String]
    .map(Bar.apply)
}
// barDecoder: Decoder[Bar] = cats.xml.codec.Decoder$$anonfun$of$2@50811bba

x.as[Bar]
// res0: Decoder.Result[Bar] = Valid(a = Bar(v = "1"))
```

I think I would expect this code to preserve `01` since I used `.as[String]` on the node `bar`, but it ends up as just `1`.

Maybe I am misunderstanding, thanks for the reply.

**Comment by geirolz** [comment]
Thanks for the clarification! 
I'd say it's a bug. Not related to the `Cursor` itself but from this 

```scala
val x = xml"""
    <foo>
      <bar>01</bar>
    </foo>
  """
```

The `01` is parsed as `XmlInt`. Since the value fits the `Int` type.
`XmlString` is used as a fallback incase the value doesn't fits any other type.

[Xml.scala:94](https://github.com/geirolz/cats-xml/blob/064b74d84ee0c575eb1c347fc827219de1785c75/core/src/main/scala/cats/xml/Xml.scala#L94C10-L94C10)
```scala
def fromDataString(value: String): XmlData = {
    fromNumberString(value)
      .getOrElse {
        val strData = Xml.ofString(value)
        Decoder
          .oneOf(
            Decoder.decodeBoolean.map(Xml.ofBoolean),
            Decoder.decodeChar.map(Xml.ofChar)
          )
          .decode(strData)
          .getOrElse(strData)
      }
  }
```

Maybe it's better to just use `XmlString` for all values during the string parsing and leave the conversion in charge of the `Cursor`. I wonder the implication of this change

**Comment by Deliganli** [comment]
Maybe it can break for anyone was relying on using `XmlInt` in pattern matching right after parse and without decoders. But I believe it is a better direction to preserve it. 
Thanks and cheers
