### ISSUE TITLE
Add example for decoding list of nodes

### ISSUE THREAD

**Issue by Deliganli** [geirolz/cats-xml#137]
There are usually list of same named nodes in the XMLs I often interact with. Such as below

```xml
<foo>
  <bar>
    <baz>1</baz>
  </bar>
  <bar>
    <baz>2</baz>
  </bar>
  <bar>
    <baz>3</baz>
    <qux>A</qux>
  </bar>
</foo>
```

Couldn't figure out how to parse those list of `bar` s when writing decoders from cursors.

```scala
case class Baz(v: String)

implicit val bazD: Decoder[Baz] =
  Decoder.fromCursor(_.text.as[String]).map(Baz)

case class Qux(v: String)

implicit val quxD: Decoder[Qux] =
  Decoder.fromCursor(_.text.as[String]).map(Qux)

case class Bar(baz: Baz, qux: Option[Qux])

implicit val barD: Decoder[Bar] =
  Decoder.fromCursor { c =>
    (
      c.down("baz").as[Baz],
      c.down("qux").as[Option[Qux]]
    ).mapN(Bar.apply)
  }

case class Foo(bar: List[Bar])

implicit val fooD: Decoder[Foo] =
  Decoder.fromCursor { c =>
    c.down("bar")
      .as[???] // How to decode the list of nodes here?
      .map(Foo.apply)
  }
```

` .as[List[Bar]]` doesn't work because `List` decoders are expecting comma separated strings as I understand.

Maybe we can add an example to decoders to how to decode such nodes.

**Comment by geirolz** [comment]
Nice spot. This is actually a problem.
I've just opened a PR to fix this providing a prover `Decoder[List[T]]` implementation.

Let me know what do you think about it 

https://github.com/geirolz/cats-xml/pull/138
